-- MySQL Script generated by MySQL Workbench
-- Thu May 28 13:53:32 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema atividadesaeb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `atividadesaeb` ;

-- -----------------------------------------------------
-- Schema atividadesaeb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atividadesaeb` DEFAULT CHARACTER SET utf8 ;
USE `atividadesaeb` ;

-- -----------------------------------------------------
-- Table `atividadesaeb`.`produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `atividadesaeb`.`produtos` ;

CREATE TABLE IF NOT EXISTS `atividadesaeb`.`produtos` (
  `idprodutos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `valor` DECIMAL NOT NULL,
  `quantidade` INT NOT NULL,
  `categoria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idprodutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividadesaeb`.`movimentacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `atividadesaeb`.`movimentacoes` ;

CREATE TABLE IF NOT EXISTS `atividadesaeb`.`movimentacoes` (
  `idmovimentacoes` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  `quantidade` INT NOT NULL,
  `produtos_idprodutos` INT NOT NULL,
  PRIMARY KEY (`idmovimentacoes`),
  INDEX `fk_movimentacoes_produtos_idx` (`produtos_idprodutos` ASC) VISIBLE,
  CONSTRAINT `fk_movimentacoes_produtos`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `atividadesaeb`.`produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


